# Generated by Django 5.2.16 on 2026-07-29 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0016_globalresponse_source_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('module_id', models.CharField(blank=True, default='', max_length=200)),
                ('content_id', models.CharField(blank=True, default='', max_length=200)),
                ('role', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hive.moxiedevice')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'timestamp'], name='transcript_device_ts_idx')],
            },
        ),
    ]
