# Generated by Django 5.2.16 on 2026-07-29 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0017_chattranscript'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=40)),
                ('key', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('confidence', models.FloatField(default=0.5)),
                ('times_seen', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hive.moxiedevice')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'bank', 'active'], name='fragment_device_bank_idx')],
                'unique_together': {('device', 'bank', 'key')},
            },
        ),
    ]
