# Generated by Django 5.2.16 on 2026-07-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0018_memoryfragment'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryfragment',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
