# Generated by Django 5.2.16 on 2026-07-30 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0019_memoryfragment_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSessionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=200)),
                ('history', models.JSONField(default=list)),
                ('total_volleys', models.IntegerField(default=0)),
                ('local_data', models.JSONField(default=dict)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hive.moxiedevice')),
            ],
        ),
    ]
