# Generated by Django 5.2.16 on 2026-07-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0020_chatsessionstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryfragment',
            name='last_surfaced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memoryfragment',
            name='surfaced_count',
            field=models.IntegerField(default=0),
        ),
    ]
