# Generated by Django 5.2.16 on 2026-07-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0021_memoryfragment_last_surfaced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryfragment',
            name='origin',
            field=models.CharField(default='extracted', max_length=16),
        ),
    ]
